syntax = "proto3";
package ergors.actions.v1;

import "google/protobuf/any.proto";
import "asset/v1/asset.proto";
import "fee/v1/fee.proto";
import "sct/v1/sct.proto";
import "keys/v1/keys.proto";
import "orch/v1/orch.proto";
import "txhash/v1/txhash.proto";
import "decaf377_fmd/v1/decaf377_fmd.proto";
import "decaf377_rdsa/v1/decaf377_rdsa.proto";
import "tct/v1/tct.proto";
message PromptPlan {
 
}


// A Ergors transaction.
message Transaction {
  TransactionBody body = 1;
  // The binding signature is stored separately from the transaction body that it signs.
  decaf377_rdsa.v1.BindingSignature binding_sig = 2;
  // The root of some previous state of the state commitment tree, used as an anchor for all
  // ZK state transition proofs.
  tct.v1.MerkleRoot anchor = 3;
}

// The body of a transaction.
message TransactionBody {
  // A list of actions (state changes) performed by this transaction.
  repeated Action actions = 1;
  // Parameters determining if a transaction should be accepted by this chain.
  TransactionParameters transaction_parameters = 2;
  // The encrypted memo for this transaction.
  //
  // This field will be present if and only if the transaction has outputs.
  MemoCiphertext memo = 5;
}

// The parameters determining if a transaction should be accepted by the chain.
message TransactionParameters {
  // The maximum height that this transaction can be included in the chain.
  //
  // If zero, there is no maximum.
  uint64 expiry_height = 1;
  // The chain this transaction is intended for.  Including this prevents
  // replaying a transaction on one chain onto a different chain.
  string chain_id = 2;
}

// Represents a transaction summary containing multiple effects.
message TransactionSummary {
 
}

// Detection data used by a detection server performing Fuzzy Message Detection.
message DetectionData {
  // A list of clues for use with Fuzzy Message Detection.
  repeated decaf377_fmd.v1.Clue fmd_clues = 4;
}


 
// A state change performed by a transaction.
message Action {
  oneof action {
  ergors.orch.v1.PromptRequest prompt = 1;
  }
}

// A transaction perspective is a bundle of key material and commitment openings
// that allow generating a view of a transaction from that perspective.
message TransactionPerspective {
  repeated PayloadKeyWithCommitment payload_keys = 1;
  repeated NullifierWithNote spend_nullifiers = 2;
  // The openings of note commitments referred to in the transaction
  // but not included in the transaction.
  // Any relevant address views.
  repeated keys.v1.AddressView address_views = 4;
  // Any relevant denoms for viewed assets.
  repeated asset.v1.Metadata denoms = 5;
 

 
  message ExtendedMetadataById {
    ergors.asset.v1.AssetId asset_id = 1;
    google.protobuf.Any extended_metadata = 2;
  }
  // Any relevant extended metadata, indexed by asset id.
  repeated ExtendedMetadataById extended_metadata = 30;

  // Associates a nullifier with the transaction ID that created the nullified state commitment.
  //
  // Note: this is _not_ the transaction ID that revealed the nullifier.
  //
  // Allows walking backwards from a spend to the transaction that created the note.
  message CreationTransactionIdByNullifier {
    sct.v1.Nullifier nullifier = 1;
    txhash.v1.TransactionId transaction_id = 2;
  }
  repeated CreationTransactionIdByNullifier creation_transaction_ids_by_nullifier = 40;

  // Associates a commitment with the transaction ID that eventually nullified it.
  //
  // Allows walking forwards from an output to the transaction that spent the note.
  message NullificationTransactionIdByCommitment {
    tct.v1.StateCommitment commitment = 1;
    txhash.v1.TransactionId transaction_id = 2;
  }
  repeated NullificationTransactionIdByCommitment nullification_transaction_ids_by_commitment = 50;

 

  keys.v1.PositionMetadataKey position_metadata_key = 70;
}

message PayloadKeyWithCommitment {
  keys.v1.PayloadKey payload_key = 1;
  tct.v1.StateCommitment commitment = 2;
}

message NullifierWithNote {
  sct.v1.Nullifier nullifier = 1;
}

// View of a Penumbra transaction.
message TransactionView {
  // View of the transaction body
  TransactionBodyView body_view = 1;
  // The binding signature is stored separately from the transaction body that it signs.
  decaf377_rdsa.v1.BindingSignature binding_sig = 2;
  // The root of some previous state of the state commitment tree, used as an anchor for all
  // ZK state transition proofs.
  tct.v1.MerkleRoot anchor = 3;
}

message TransactionBodyView {
  // A list views into of actions (state changes) performed by this transaction.
  repeated ActionView action_views = 1;
  // Transaction parameters.
  TransactionParameters transaction_parameters = 2;
  // The detection data in this transaction, only populated if
  // there are outputs in the actions of this transaction.
  DetectionData detection_data = 4;
  // An optional view of a transaction memo. It will only be populated if there are
  // outputs in the actions of this transaction.
  MemoView memo_view = 5;
}

// A view of a specific state change action performed by a transaction.
message ActionView {
  oneof action_view {
  ergors.orch.v1.PromptRequest prompt = 1;
  }
}

// The data required to authorize a transaction plan.
message AuthorizationData {
  // The computed auth hash for the approved transaction plan.
  txhash.v1.EffectHash effect_hash = 1;
  // The required spend authorizations, returned in the same order as the
  // Spend actions in the original request.
  repeated decaf377_rdsa.v1.SpendAuthSignature spend_auths = 2;
  // The required delegator vote authorizations, returned in the same order as the
  // DelegatorVote actions in the original request.
  repeated decaf377_rdsa.v1.SpendAuthSignature delegator_vote_auths = 3;
  // The required LQT vote authorizations, in the same order as the original request.
  repeated  decaf377_rdsa.v1.SpendAuthSignature lqt_vote_auths = 4;
}

// The data required for proving when building a transaction from a plan.
message WitnessData {
  // The anchor for the state transition proofs.
  tct.v1.MerkleRoot anchor = 1;
  // The auth paths for the notes the transaction spends, in the
  // same order as the spends in the transaction plan.
  repeated  tct.v1.StateCommitmentProof state_commitment_proofs = 2;
}

// Describes a planned transaction. Permits clients to prepare a transaction
// prior submission, so that a user can review it prior to authorizing its execution.
//
// The `TransactionPlan` is a fully determined bundle binding all of a transaction's effects.
// The only thing it does not include is the witness data used for proving.
message TransactionPlan {
  // The sequence of actions planned for this transaction.
  repeated ActionPlan actions = 1;
  // Parameters determining if a transaction should be accepted by this chain.
  TransactionParameters transaction_parameters = 2;
  // Detection data for use with Fuzzy Message Detection
  DetectionDataPlan detection_data = 4;
  // The memo plan for this transaction.
  MemoPlan memo = 5;
}


// Describes a plan for forming a `Clue`.
message CluePlan {
  // The address.
  keys.v1.Address address = 1;
  // The random seed to use for the clue plan.
  bytes rseed = 2;
  // The bits of precision.
  uint64 precision_bits = 3;
}


message DetectionDataPlan {
  repeated CluePlan clue_plans = 5;
}

// Describes a planned transaction action.
//
// Some transaction Actions don't have any private data and are treated as being plans
// themselves.
message ActionPlan {
  oneof action {
    PromptPlan prompt = 1;
    
  }
}

 
// Describes a plan for forming the transaction memo.
message MemoPlan {
  // The plaintext.
  MemoPlaintext plaintext = 1;
  // The key to use to encrypt the memo.
  bytes key = 2;
}

// The encrypted memo data describing information about the purpose of a transaction.
message MemoCiphertext {
  // The encrypted data. 528 bytes.
  bytes inner = 1;
}

// The plaintext describing information about the purpose of a transaction.
message MemoPlaintext {
  // The sender's return address.
  //
  // This should always be a valid address; the sender is responsible for ensuring
  // that if the receiver returns funds to this address, they will not be lost.
  string return_address = 1;
  // Free-form text, up to 432 bytes long.
  string text = 2;
}

message MemoPlaintextView {
  ergors.keys.v1.AddressView return_address = 1;
  string text = 2;
}

message MemoView {
  message Visible {
    MemoCiphertext ciphertext = 1;
    MemoPlaintextView plaintext = 2;
  }

  message Opaque {
    MemoCiphertext ciphertext = 1;
  }
  oneof memo_view {
    Visible visible = 1;
    Opaque opaque = 2;
  }
}
