---
version: "2.0"
services:
  ergors:
    image: ghcr.io/permissionlessweb/ergors:latest
    expose:
      - port: 8080
        as: 80
        to:
          - global: true
      - port: 50051
        as: 50051
        proto: tcp
        to:
          - global: true
      - port: 26969
        as: 26969
        proto: tcp
        to:
          - global: true
    env:
      - ERGORS_ADMIN_PUBKEY=REPLACE_WITH_YOUR_ADMIN_PUBKEY_HEX
      - ERGORS_API_PORT=8080
      - ERGORS_GRPC_PORT=50051
      - NODE_TYPE=NODE_TYPE_EXECUTOR
      - P2P_PORT=26969
profiles:
  compute:
    ergors:
      resources:
        cpu:
          units: 2
        memory:
          size: 4Gi
        storage:
          - size: 20Gi
  placement:
    akash:
      pricing:
        ergors:
          denom: uakt
          amount: 10000
deployment:
  ergors:
    akash:
      profile: ergors
      count: 1
